### PR TITLE
Validate linter results and refactor EditorLinter::lintResults

### LINKED ISSUE #36: Validate linter results
If linters leave out the `type` property it throws an exception.

selection_070

^ This error can prevent you from switching tabs

### PR DESCRIPTION
**Pull request by AsaAyers**
Fixes #36

### CODE REVIEW

File: lib/editor-linter.coffee [hunk 1]
```diff
@@ -1,5 +1,15 @@
 {CompositeDisposable, Emitter} = require 'atom'
 
+validateResults = (results) ->
```
Comment (steelbrain) [inline lib/editor-linter.coffee]: you could've made it a class static method or something, it looks un-beautiful this way.
It is the only method of it's kind in the whole project.

Comment (AsaAyers) [inline lib/editor-linter.coffee]: Just call it ugly. Let's drop thus Un beautiful nonsense

Comment (steelbrain) [inline lib/editor-linter.coffee]: Calling something ugly is rude. so I avoid that word as much as I can.

Comment (AsaAyers) [inline lib/editor-linter.coffee]: Do you have any objective reasons you don't like this?

Sure, I could make this a method on the class, but it doesn't need access to the class.

I could make it a static method on the class, but it doesn't need to be exposed to any code outside this module. it also doesn't need the class.

I could define this inline like I did for the `.then(...)`s and `.catch(...)` but it doesn't need any of the variables closured in. There is also some amount of overhead every time a function is created. Having a function here that doesn't need to closure in any variables is the ideal solution to this exact problem.

Comment (AsaAyers) [inline lib/editor-linter.coffee]: Everyone can see through "un-beautiful" so IMO it's no less rude than calling it ugly

Comment (steelbrain) [inline lib/editor-linter.coffee]: It just doesn't look right the way it is right now, so having it as a static method would work I guess, because it would only be created once and will not have access to this and will have zero overhead. The point to be noted is that it'll be exposed, and I don't see anything bad about it.

Comment (AsaAyers) [inline lib/editor-linter.coffee]: > It just doesn't look right the way it is right now

seriously. how much Javascript experience do you have? I'm talking on the clock working full time for a company gettting paid to write javascript. Not meessing around for fun?

There's nothing wrong with this, it's just not the one style you're familiar with.

Comment (steelbrain) [inline lib/editor-linter.coffee]: > seriously. how much Javascript experience do you have?

Can you please stop treating me like a child? I have enough experience with javascript to write my own javascript engine in it.

> There's nothing wrong with this, it's just not the one style you're familiar with.

I know there's nothing wrong with this, but I am showing you a better way.
Option 1: put a method at the start of the file and put a class in the rest of it
Option 2: Add that method to the class

Option 2 is much cleaner and preferable.

Comment (AsaAyers) [inline lib/editor-linter.coffee]: I'm not going to keep having these stupid arguments with you. This kind of
crap is why I was planning to leave this morning

Comment (steelbrain) [inline lib/editor-linter.coffee]: and there we go again. Man. You should practice being calm sometimes. :-)

Comment (AsaAyers) [inline lib/editor-linter.coffee]: I am calm. Your Un beautiful complaints are not productive and are
irritating

Comment (steelbrain) [inline lib/editor-linter.coffee]: Hahaha, don't worry, I'll sort them out myself.
